/**
 * Curated list of popular Google Font family names for the font-picker
 * field. Not the full ~1700-family catalog — a representative set across
 * sans, serif, display, and monospace so the picker has something useful
 * to search without shipping/maintaining a giant metadata blob. Each
 * family is requested from Google's CSS2 API on demand (see
 * SiteShell.vue::applyFontFamily), never bundled as font files.
 */
export const googleFonts = [
  'Inter',
  'Roboto',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Poppins',
  'Nunito',
  'Nunito Sans',
  'Source Sans 3',
  'Work Sans',
  'Rubik',
  'Manrope',
  'DM Sans',
  'Karla',
  'Mulish',
  'Figtree',
  'Plus Jakarta Sans',
  'Outfit',
  'Space Grotesk',
  'Sora',
  'Albert Sans',
  'Urbanist',
  'Public Sans',
  'IBM Plex Sans',
  'Barlow',
  'Cabin',
  'Hanken Grotesk',
  'Lexend',
  'Jost',
  'Red Hat Display',
  'Playfair Display',
  'Merriweather',
  'Lora',
  'PT Serif',
  'Crimson Text',
  'Source Serif 4',
  'Libre Baskerville',
  'Cormorant Garamond',
  'EB Garamond',
  'Bitter',
  'Domine',
  'Fraunces',
  'Newsreader',
  'Spectral',
  'Frank Ruhl Libre',
  'Josefin Sans',
  'Quicksand',
  'Comfortaa',
  'Raleway',
  'Oswald',
  'Bebas Neue',
  'Archivo',
  'Archivo Black',
  'Anton',
  'Righteous',
  'Fjalla One',
  'Abril Fatface',
  'Cormorant',
  'Zilla Slab',
  'IBM Plex Mono',
  'JetBrains Mono',
  'Space Mono',
  'Roboto Mono',
  'Fira Code',
  'Source Code Pro',
  'Courier Prime',
  'Instrument Sans',
  'Instrument Serif',
  'Bricolage Grotesque',
];
